New plugin spraymon
tklengyel/drakvuf pull request #1397
Opened 2022-02-24 17:07 UTC by BlindingRadiance

Hi! I've made a new plugin `spraymon`. It's purpose is to detect possible spray attempts using win32k graphic objects by checking counters inside [W32PROCESS](https://www.geoffchappell.com/studies/windows/km/win32k/structs/processinfo/index.htm) structure. Since this structure is not really documented, symbol information is available only for Windows 7 and Windows 10 (>=1607). 
Checks are made when W32PROCESS information is being deleted from EPROCESS and at the end of the analysis.

2022-02-24 17:12 UTC, tklengyel commented on src/plugins/spraymon/spraymon.cpp
> +* DRAKVUF (C) 2014-2021 Tamas K Lengyel.                                  *
2022

2022-02-24 17:12 UTC, tklengyel commented on src/plugins/spraymon/spraymon.cpp
> +//     } while (0)
Remove this commented-out block if you don't use it anymore. You can also leave it in and just wrap it in an `ifdef DRAKVUF_DEBUG` block.

2022-02-24 17:12 UTC, tklengyel commented on src/plugins/spraymon/spraymon.h
> + * DRAKVUF (C) 2014-2021 Tamas K Lengyel.                                  *
2022

2022-02-24 17:13 UTC, tklengyel commented
Nice to see such quality submission on a first PR! :) LGTM, please fix the issues spotted by the CI and the couple comments I left and we can merge.

2022-02-24 17:26 UTC, BlindingRadiance commented
Thanks!

2022-03-06 01:41 UTC, tklengyel commented
@drakvuf-jenkins This is OK to test

2022-03-06 02:09 UTC, tklengyel commented on src/plugins/spraymon/spraymon.cpp
> +        throw -1;
Don't `throw` here if no win32k profile is set, just return gracefully.

2022-03-06 23:19 UTC, BonusPlay requested changes
Nice code overall :)

2022-03-06 23:19 UTC, BonusPlay commented on src/plugins/spraymon/spraymon.cpp
> +}
Do not declare empty dctor, it has certain implications.

2022-03-06 23:19 UTC, BonusPlay commented on src/plugins/spraymon/spraymon.h
> +public:
no need to make everything public

2022-03-06 23:19 UTC, BonusPlay commented on src/plugins/spraymon/spraymon.cpp
> +void spraymon::compare(drakvuf_t drakvuf, uint16_t gdi_max_count, uint16_t usr_max_count, char* process_name, vmi_pid_t pid)
misleading name as it doesn't really compare stuff, main reason is to output some log.

2022-03-09 17:28 UTC, tklengyel commented
@drakvuf-jenkins Retest this please

2022-03-09 18:06 UTC, BlindingRadiance commented
Weird the error didn't show up on my local build.

2022-03-11 15:04 UTC, merged